SKILLS = {
    "Web Developer": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "vue.js",
        "node.js",
        "express.js",
        "rest api",
        "graphql",
        "git",
        "webpack",
        "docker",
        "sql",
        "mongodb",
        "responsive design",
        "jest",
        "ci/cd"
    ],
    "AI/ML Engineer": [
        "python",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "keras",
        "numpy",
        "pandas",
        "machine learning",
        "deep learning",
        "natural language processing",
        "computer vision",
        "mlops",
        "docker",
        "kubernetes",
        "hugging face",
        "cuda",
        "model deployment",
        "feature engineering",
        "git"
    ],
    "Data Scientist": [
        "python",
        "sql",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "scikit-learn",
        "statistical analysis",
        "data wrangling",
        "data visualization",
        "hypothesis testing",
        "machine learning",
        "tableau",
        "power bi",
        "excel",
        "spark",
        "hadoop",
        "jupyter notebook"
    ]
}