SKILLS = {
    "Web Developer": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "vue.js",
        "node.js",
        "express.js",
        "rest api",
        "graphql",
        "git",
        "webpack",
        "docker",
        "sql",
        "mongodb",
        "responsive design",
        "jest",
        "ci/cd"
    ],
    "AI/ML Engineer": [
        "python",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "keras",
        "numpy",
        "pandas",
        "machine learning",
        "deep learning",
        "natural language processing",
        "computer vision",
        "mlops",
        "docker",
        "kubernetes",
        "hugging face",
        "cuda",
        "model deployment",
        "feature engineering",
        "git"
    ],
    "Data Scientist": [
        "python",
        "sql",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "scikit-learn",
        "statistical analysis",
        "data wrangling",
        "data visualization",
        "hypothesis testing",
        "machine learning",
        "tableau",
        "power bi",
        "excel",
        "spark",
        "hadoop",
        "jupyter notebook"
    ],

    "Data Analyst": [
        "sql",
        "excel",
        "python",
        "pandas",
        "numpy",
        "power bi",
        "tableau",
        "data visualization",
        "statistics",
        "data cleaning",
        "pivot tables",
        "vlookup",
        "google sheets",
        "matplotlib",
        "seaborn",
        "reporting",
        "dashboard",
        "business intelligence"
    ],
    "DevOps Engineer": [
        "docker",
        "kubernetes",
        "jenkins",
        "ci/cd",
        "linux",
        "bash",
        "git",
        "aws",
        "azure",
        "gcp",
        "terraform",
        "ansible",
        "nginx",
        "monitoring",
        "prometheus",
        "grafana",
        "networking",
        "shell scripting"
    ],
    "Backend Developer": [
        "python",
        "java",
        "node.js",
        "express.js",
        "django",
        "flask",
        "fastapi",
        "rest api",
        "graphql",
        "sql",
        "postgresql",
        "mongodb",
        "redis",
        "docker",
        "git",
        "microservices",
        "authentication",
        "aws"
    ],
    "Android Developer": [
        "java",
        "kotlin",
        "android studio",
        "xml",
        "firebase",
        "rest api",
        "git",
        "retrofit",
        "mvvm",
        "jetpack compose",
        "room database",
        "google play",
        "material design",
        "gradle",
        "unit testing"
    ]

    
}